# Generated by Django 4.1 on 2022-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_alter_customer_cnpj_alter_customer_rg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
